include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore
    unnecessary_new: ignore
    use_key_in_widget_constructors: ignore

linter:
  rules:
    prefer_const_constructors: false
